services:
  postgres:
    image: postgres:16
    container_name: pg-queue-db
    environment:
      POSTGRES_USER: pgqueue
      POSTGRES_PASSWORD: pgqueue
      POSTGRES_DB: pgqueue
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgqueue -d pgqueue"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
